ykdl/extractors/panda.py

This will fix some streams not working.

Fix for some streams on panda.tv.

---

ykdl/util/download.py

#62 
进度条显示会变的奇怪，但是目前没找到更好的办法解决

multi thread downloading

---

README.rst

Reverts zhangn1985/ykdl#14
no one uses gitter...

Revert "Add a Gitter chat badge to README.rst"

---

ykdl/extractors/youku.py

先是发现这种无法匹配 `https://players.youku.com/player.php/sid/....../v.swf`。
修改时看见有重复就一并修复了。

Update youku match

---

ykdl/extractors/qq/video.py

try to fix 
https://github.com/zhangn1985/ykdl/issues/268

fix #268 download qq video fail

---

ykdl/util/download.py

Reverts zhangn1985/ykdl#353
clsoe #354

Revert "fix download status #352"

---

ykdl/util/jsengine.py

写了一个简单的wrapper，调用系统自带的JS解析器执行Javascript，macOS下调用自带的JavaScriptCore，Linux下调用Gnome的gjs、Cinnamon的cjs或者NodeJS
Windows下的还没写，如果你们觉得可以的话我再把Windows下的加上
用JS就可以解析优酷爱奇艺了 #370  #314

Add Javascript interpreter

---

ykdl/util/jsengine.py
ykdl/util/jsengine_chakra.py

Add chakra javascript interpreter

---

ykdl/extractors/douyu/live.py

m.douyu.com
douyu.com
www.douyu.com
etc...

match 3 level domains of douyu

---

ykdl/util/jsengine.py

Also add JavaScriptCore on Linux, which is a part of webkitgtk

jsengine: Fix print function in nodejs

---

ykdl/extractors/pps.py

qixiu: add support

---

cykdl/__main__.py
ykdl/util/wrap.py

Fix concat issue

---

ykdl/extractors/douyu/live.py

测试房间https://www.douyu.com/96291

添加一个msi期间，斗鱼个别房间id获取正则

---

ykdl/common.py
ykdl/extractors/acfun/__init__.py
ykdl/extractors/baidu/__init__.py
ykdl/extractors/bilibili/__init__.py
ykdl/extractors/douban/__init__.py
ykdl/extractors/douyu/__init__.py
ykdl/extractors/huajiao/__init__.py
ykdl/extractors/huya/__init__.py
ykdl/extractors/ifeng/__init__.py
ykdl/extractors/iqiyi/__init__.py
ykdl/extractors/le/__init__.py
ykdl/extractors/netease/__init__.py
ykdl/extractors/netease/music/__init__.py
ykdl/extractors/qq/__init__.py
ykdl/extractors/sina/__init__.py
ykdl/extractors/sohu/__init__.py

以支持重组 URL，方便 sub-extractor 使用。

Refactor get_extractor

---

ykdl/extractors/zhuafan.py

Adding zhuafan.live live streaming site support

Adding zhuafan.live support

---

ykdl/util/jsengine.py

'-5', not '-3'
https://github.com/zhangn1985/ykdl/issues/398#issuecomment-541663300

error on MacOS

---

cykdl/__main__.py
ykdl/compact.py
ykdl/extractors/bobo.py
ykdl/extractors/mgtv.py
ykdl/util/html.py
ykdl/util/rangefetch_server.py
ykdl/util/wrap.py

#434 wrote wrong codes, fix it.

Socks proxy

---

ykdl/util/download.py
ykdl/util/wrap.py

* fix download non-206 support
* fix merge commands too long
才反应过来脚本内就能使用管道，即使没有 cat，Windows 也能用 #399 提到的方法。
请测试其它系统的使用情况。

fix some downloads issues #399 #404

---

ykdl/extractors/douyu/live.py

fix #542
另外没发现原来的蓝光10M、蓝光8M、蓝光和流畅。

adjust douyu stream profile ids

---

ykdl/extractors/douyu/video.py

add douyu video super stream id

---

cykdl/__main__.py
ykdl/extractors/netease/__init__.py
ykdl/extractors/netease/live.py
ykdl/extractors/netease/livecc.py
ykdl/extractors/netease/openc.py
ykdl/extractors/netease/video.py
ykdl/util/wrap.py
ykdl/videoinfo.py

https://open.163.com/ 有提供字幕，我尝试增加支持。请大家空闲的时候看一下，如果这个结构有什么不合适的地方，烦请指出。

Add subtitles support

---

ykdl/extractors/douyu/live.py

Fix for douyu live's `KeyError: '原画1080P60'`
Feel free to edit the name `OG1080P60`

douyu live 1080p60

---

ykdl/extractors/bilibili/live.py

bilibili.live: Change api
